name: CI
'on':
  workflow_dispatch:
  schedule:
    - cron: 5 14,2 * * *
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Initiate update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ci_PAT }}
          repository: ${{ secrets.target_repo }}
          event-type: Update
          client-payload: '{"success": true}'
